---
title: "PS 2"
subtitle: "ARE 212, Spring 2026"
author: "David Cai, Miriam Gold, Ella Moxley, Geoffrey Yip"
date: "13 March 2026"
format: pdf
mainfont: "Palatino"
sansfont: "Palatino"
---


```{r}
library(tidyverse)
library(haven)

path <- "~/projects/ARE212_2026/ps2"
path_data <- file.path(path, "data")

```

# Q1


```{r}
data_nerlove <- read_dta(file.path(path_data, "nerlove.dta"))

data_nerlove_clean <-
    data_nerlove %>%
    # Sort by kwh
    arrange(q) %>%
    # Delete anomalous wage observation
    filter(pl < 180)

```

# Q2

```{r}
# Replicate regression I of Table 3 (p. 176) in the paper
# first log the varibales 
data_reg <- 
    data_nerlove_clean %>%
  mutate(
    ltc = log(tc),
    lq  = log(q),
    lpl = log(pl),
    lpf = log(pf),
    lpk = log(pk),
    Y = lq,
    P1P3 = lpl - lpf,
    P2P3 = lpk - lpf, # k minus fuel
    CP3 = ltc - lpf
  )

reg1 <- lm( CP3 ~ Y + P1P3 + P2P3, data = data_reg)

```

# Q3
Conduct the hypothesis test using CRS (i.e., $\beta_y = 1$).
```{r}
#t = betahat - beta0/SE

betahat <- coef(reg1)["Y"]
se <- summary(reg1)$coefficients["Y", "Std. Error"]
t_stat <- (betahat - 1) / se
pval <- 1-pt(abs(t_stat), df = nrow(data_reg)-4)
print(paste("P-value of \beta_y is", pval))
```

Our point estimate is significant at the 0.01 level, so we likely have increasing returns to scale, since $r = \frac{1}{0.71} > 1$ 

# Q4

```{r}
data_reg %>%
    mutate(resid = reg1$residuals) %>%
    ggplot(aes(lq, resid)) + 
    geom_point() +
    labs(
        x = "Log output",
        y = "Residuals"
    ) +
    theme_bw()
```

The uneven spread of the residuals over the range of output indicates that homoskedasticity is violated. From an economic perspective, 

# Q5

# Q6

# Q7

# Q8

